### ISSUE TITLE
Ability to list ignored files

### ISSUE THREAD

**Issue by korve** [samuelmeuli/tmignore#3]
Right now i don't see the ignored files in the macOS Timemachine GUI. Is it possible that tmignore lists the ignored files?

running tmignore added 341 files:
2019-10-21T10:42:57+0200 info: Identified 341 paths to exclude from backups
2019-10-21T10:42:57+0200 info: Excluding 341 files/directories from future backups…

**Comment by korve** [comment]
Nvm... no files were added by tmignore.

**Comment by samuelmeuli** [comment]
When using the `tmutils` command to exclude files (which `tmignore` does internally), they unfortunately don't show up in the System Preferences: https://apple.stackexchange.com/questions/222346/time-machine-exclusions-added-via-tmutil-do-not-appear-in-tm-options-list.

Right now, you can run `tmutil isexcluded FILE_PATH` to check whether a file/directory has been excluded, or look at the cache at `~/Library/Caches/tmignore/cache.json`.

Adding a `tmignore list` command or a `tmignore run --verbose` flag is probably a good idea. I'll look into that :)

**Comment by samuelmeuli** [comment]
The `list` command will be available in the next release.
