### ISSUE TITLE
Unable to install: full installation of Xcode required

### ISSUE THREAD

**Issue by exhtml** [samuelmeuli/tmignore#4]
Hi! I found very useful your tool and I wanted to give it a try but when I try to install it:
`brew install samuelmeuli/tap/tmignore`
Homebrew throws this error:
`A full installation of Xcode.app 10.0 is required to compile
this software. Installing just the Command Line Tools is not sufficient.`
Am I doing something wrong or truly I need to have full Xcode installed in order tu install and run tmignore? I'm using MacOSX Mojave.
Thank you very much for your help!

**Comment by samuelmeuli** [comment]
Hi @exhtml, Xcode is required for compiling the `tmignore` Swift code on your machine. Homebrew downloads the Git repo (not the binary) and builds it locally. You should be able to remove Xcode once `tmignore` has been installed.

I'm not sure if Swift is included in `xcode-select` and if that tool would be sufficient to build the binary. But unfortunately, it's not currently possible to specify `xcode-select` as a dependency for a Homebrew formula.

**Comment by samuelmeuli** [comment]
You can now download a pre-built binary from the [Releases](https://github.com/samuelmeuli/tmignore/releases) page.

**Comment by exhtml** [comment]
Good news! Thank you very much for your work! Hope you are well, I'll give
it a try. Cheers!
