### ISSUE TITLE
Installation via homebrew fails (missing xctest)

### ISSUE THREAD

**Issue by Baloobear** [samuelmeuli/tmignore#6]
Hi,

I tried to install the tool as described in project readme.

```
$ brew install samuelmeuli/tap/tmignore
==> Tapping samuelmeuli/tap
Cloning into '/usr/local/Homebrew/Library/Taps/samuelmeuli/homebrew-tap'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 40 (delta 17), reused 33 (delta 10), pack-reused 0
Receiving objects: 100% (40/40), 10.13 KiB | 5.06 MiB/s, done.
Resolving deltas: 100% (17/17), done.
Tapped 1 formula (28 files, 37.4KB).
==> Installing tmignore from samuelmeuli/tap
==> Downloading https://github.com/samuelmeuli/tmignore/archive/v1.1.1.tar.gz
==> Downloading from https://codeload.github.com/samuelmeuli/tmignore/tar.gz/v1.1.1
######################################################################## 100.0%
==> make build
Last 15 lines from /Users/dennis/Library/Logs/Homebrew/tmignore/01.make:
2020-03-25 14:18:01 +0100

make
build

swift build --configuration release --disable-sandbox
error: terminated(72): xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH

make: *** [build] Error 1
``` 

I am running macOS 10.15.3 (with current Xcode 11.3.1).

Do you have an idea what's going wrong here? I don't have installed any special Xcode tools, yet, but only did `xcode-select --install` once some time ago.
Any help is appreciated.

Greetings,
Dennis

**Comment by samuelmeuli** [comment]
Hi @Baloobear,

You'll need a full installation of Xcode to compile `tmignore` when installing it using Homebrew (see #4).

**Comment by Baloobear** [comment]
Thanks for your quick reply.

I'm not sure what "full installation of Xcode" means but I have the Xcode application fully running (not just the command line tools). I installed it from the App Store (and also just updated it to version 11.4).

Is anything missing?

**Comment by samuelmeuli** [comment]
Did you try [this](https://github.com/mxcl/homebrew-made/issues/1#issuecomment-453757503)?

**Comment by Baloobear** [comment]
Hi @samuelmeuli,

thanks for this. This solved the issue and the installation (resp. build) was now successful.

But how should one know to do this?!? Strange...

**Comment by samuelmeuli** [comment]
Great! You shouldn't normally have to do this, I don't know why the path was incorrect in your case.
