### ISSUE TITLE
can be build in Swift 5.0 instead of 5.1 ?

### ISSUE THREAD

**Issue by thevikas** [samuelmeuli/tmignore#7]
I have Xcode  10.3 and Swift 5.0 and I dont wish to upgrade these for many complains about biggy Xcode, besides the giga size of download which I cant do in my current setup.

Is it possible to bring the compatibility to 5.0 Swift so it can compile in my Mac?

```
xyz/tmignore: error: package at 'xyz/tmignore' is using Swift tools version 5.1.0 
but the installed version is 5.0.0
make: *** [build] Error 1
```

**Comment by samuelmeuli** [comment]
You can now download a pre-built binary from the [Releases](https://github.com/samuelmeuli/tmignore/releases) page.
