### ISSUE TITLE
Allow configuration of folder(s) to search in

### ISSUE THREAD

**Issue by thevikas** [samuelmeuli/tmignore#8]
My code base is in a different mounted partition and a specific `projects` folder. 
The run only scanned the vim plugins in home folder and done.
Can tmignore run and scan using the current folder?

**Comment by samuelmeuli** [comment]
`tmignore` currently searches [your `$HOME` directory](https://github.com/samuelmeuli/tmignore/blob/de721a75b6396ba747920d946792a916243d8d14/Sources/tmignore/Git.swift#L46) for Git repositories (and skips the directories in your whitelist). If I understand you correctly, you'd like an option to look for repos in a directory other than `$HOME`? It might make sense to add a config entry for this.

**Comment by thevikas** [comment]
Actually my Home has a symlink to my projects root.
Yes a new config entry for searchable folders would work.
Symlinks outside root disk are ignored?

**Comment by petja** [comment]
I also have my projects on separate disk partition which is symlinked to my home directory. I would appreciate to have easy configuration for the directories to search in. Another option is support for symlink following.

Great project btw – found this today! 😊

**Comment by samuelmeuli** [comment]
I've just released v1.2 with a `searchPaths` option :)
